---
kind: pipeline
name: build-arm

# ARM build (for home Raspberry Pi CI)
platform:
  os: linux
  arch: arm

# Only start on tags
trigger:
  event:
  - tag

steps:
- name: build
  image: golang:latest
  commands:
    - mkdir -p dist
    - GO111MODULE=on go mod vendor
    - export GOFLAGS="-mod=vendor -ldflags=-s -ldflags=-w"
    # Build all 386/amd64
    - |
      for goarch in 386 amd64
      do
        for goos in linux windows darwin
        do
          echo building $goos/$goarch...
          GOARCH=$goarch GOOS=$goos go build -o dist/valerius-$goos-$goarch-$DRONE_TAG
        done
      done
      echo building linux/arm...
      GOARCH=arm GOOS=linux go build -o dist/valerius-linux-arm-$DRONE_TAG
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: dist/*
    checksum:
    - sha256
